### ISSUE TITLE
snapshot and record

### ISSUE THREAD

**Issue by phid78** [dbuezas/icsee-ptz#22]
hello, 
Is there a way to send a snapshot with the alert to a gsm ?
i'd like to record video (dvrip) to my media folder , how to do this ?
i set up like this  

```
type: custom:webrtc-camera
url: clck
ui: true
shortcuts:
  services:
    - name: Sync
      icon: mdi:clock-check
      service: icsee_ptz.synchronize_clock
      service_data:
        entity_id: binary_sensor.camera_ade1_motion_alarm
    - name: Force frame
      icon: mdi:play
      service: icsee_ptz.force_frame
      service_data:
        entity_id: binary_sensor.camera_ade1_motion_alarm
    - name: record
      icon: mdi:record-circle-outline
      service: switch.toggle
      service_data:
        entity_id: switch.camera_record
mode: webrtc,mse,hls,mjpeg
ptz:
  service: icsee_ptz.move
  data_home:
    entity_id: binary_sensor.camera_ade1_motion_alarm
    cmd: GotoPreset
    preset: 1
  data_long_home:
    entity_id: binary_sensor.camera_ade1_motion_alarm
    cmd: SetPreset
    preset: 1
  data_start_left:
    entity_id: binary_sensor.camera_ade1_motion_alarm
    cmd: DirectionRight
  data_end_left:
    entity_id: binary_sensor.camera_ade1_motion_alarm
    cmd: Stop
  data_start_right:
    entity_id: binary_sensor.camera_ade1_motion_alarm
    cmd: DirectionLeft
  data_end_right:
    entity_id: binary_sensor.camera_ade1_motion_alarm
    cmd: Stop
  data_start_down:
    entity_id: binary_sensor.camera_ade1_motion_alarm
    cmd: DirectionDown
  data_end_down:
    entity_id: binary_sensor.camera_ade1_motion_alarm
    cmd: Stop
  data_start_up:
    entity_id: binary_sensor.camera_ade1_motion_alarm
    cmd: DirectionUp
  data_end_up:
    entity_id: binary_sensor.camera_ade1_motion_alarm
    cmd: Stop
muted: true

```
thanks
