### ISSUE TITLE
Multiple presets?

### ISSUE THREAD

**Issue by S2000Stefan** [dbuezas/icsee-ptz#4]
After initial difficulties for a beginner in HA like me, I finally got it running. Puhh
Wanted to ask if it is possible to set up multiple presets? One preset is good two would be better. ;)
Greetings Stefan

**Comment by dbuezas** [comment]
Sure, just pass "preset: 2" as data to the service call. The options (configure button) in the integration page are only defaults, but all can be overwritten as part of each service call

**Comment by dbuezas** [comment]
I assume you are using the webrtc card, so this should add two buttons at the top left. Double check the icon names, but it should give the idea

```yaml
shortcuts:
  services:
    - name: Set preset 2
      icon: mdi:save
      service: icsee_ptz.move
      service_data:
        entity_id: binary_sensor.garten_motion_alarm
        cmd: setPreset
        preset: 2
    - name: Goto preset 2
      icon: mdi:home
      service: icsee_ptz.move
      service_data:
        entity_id: binary_sensor.garten_motion_alarm
        cmd: gotoPreset
        preset: 2
```
