### ISSUE TITLE
No Zoom UI

### ISSUE THREAD

**Issue by nicktkd** [dbuezas/icsee-ptz#48]
Hi @dbuezas 
Thanks for this integration! Very cool stuff and helpfull

I meet an issue, maybe you can help with that.
I have a one of icsee camera  ([link](https://www.aliexpress.com/item/1005006565107298.html?spm=a2g0o.order_list.order_list_main.35.142018022gp75A))

I integrate it in WebRTC card, but I not have zoom UI
and no clock-check icon, and save icon located in diferent position
Maybe reason of that is two-camera device...

PZN and Home UI works well

![2025-01-11 174330](https://github.com/user-attachments/assets/e11f26ab-cb60-4b2f-89d0-d662bdd2329d)

Here is a code of camera card that i use. is same as in example
 
```
type: custom:webrtc-camera
url: >-
  rtsp://192.168.0.XXX:554/user=user_password=password_channel=1_stream=1.sdp?real_stream
ui: true
shortcuts:
  services:
    - name: Sync
      icon: mdi:clock-check
      service: icsee_ptz.synchronize_clock
      service_data:
        entity_id: binary_sensor.camera_06_motion_alarm
    - name: Force frame
      icon: mdi:play
      service: icsee_ptz.force_frame
      service_data:
        entity_id: binary_sensor.camera_06_motion_alarm
ptz:
  service: icsee_ptz.move
  data_home:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: GotoPreset
    preset: 0
  data_long_home:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: SetPreset
    preset: 0
  data_start_left:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: DirectionLeft
  data_end_left:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: Stop
  data_start_right:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: DirectionRight
  data_end_right:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: Stop
  data_start_down:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: DirectionDown
  data_end_down:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: Stop
  data_start_up:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: DirectionUp
  data_end_up:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: Stop

``` 

Would be happy  for any help in this case

PS Experemental - already enabled
![image](https://github.com/user-attachments/assets/b5378bb5-bcee-418c-b807-b49ae693660c)

PPS Maybe do you know any way how to separate video stream from two-camera-device into two different streams?
I try to change `channel=1_stream=1.sdp?real_stream` to different settings with 0, 1, 2  but it has no results

**Comment by nicktkd** [comment]
Zoom UI - fixed  ;)

Added this part of code  (in case if somebody will looking that)

```
  data_zoom_in:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: ZoomTile
    step: 2
  data_zoom_out:
    entity_id: binary_sensor.camera_06_motion_alarm
    cmd: ZoomWide
    step: 2
```
