### ISSUE TITLE
stop on channel 1

### ISSUE THREAD

**Issue by jazzvivi2** [dbuezas/icsee-ptz#51]
Hi. I'm using your integration to get PTZ on my cameras. They're two connected to an NVR. I managed to get both working, but the channel 1 stop doesn't work. Any ideas?

```yaml
sequence:
  - data:
      device_id: b9f8b946d4952308920b8581aa7d5fa7
      cmd: |
        {% if direction == "up" %}
          DirectionUp
        {% elif direction == "down" %}
          DirectionDown
        {% elif direction == "left" %}
          DirectionLeft
        {% elif direction == "right" %}
          DirectionRight
        {% else %}
          Stop  # Usamos el comando Stop explícitamente aquí
        {% endif %}
      channel: 1
      step: 1
    action: icsee_ptz.move
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - data:
      device_id: b9f8b946d4952308920b8581aa7d5fa7
      cmd: Stop
      channel: 1
      step: 5
    action: icsee_ptz.move
alias: PTZ 1
mode: restart
fields:
  direction:
    description: Dirección en la que se moverá la cámara
    example: up, down, left, right
    required: true
description: ""
```
