### ISSUE TITLE
NVR 8ch config with ptz

### ISSUE THREAD

**Issue by bmiki75** [dbuezas/icsee-ptz#53]
I think i have find a way to use your marvellous work with nvr and 8 channel because channel seems not passed from bynary_sensor entity

First i have to add channel in ptz config as shown 
```yaml
ptz:
  service: icsee_ptz.move
  data_home:
    entity_id: binary_sensor.nvr_motion_alarm_5
    cmd: GotoPreset
    preset: 0
   channel: 5
```
than i have to change stop method to add channel 

```python
async def async_move(self, cmd: str, **kwargs):
        step = kwargs.get("step", self.entry.options.get(CONF_STEP, 2))
        preset = kwargs.get("preset", self.entry.options.get(CONF_PRESET, 0))
        channel = kwargs.get("channel", self.entry.options.get(CONF_CHANNEL, 0))
        if cmd == "Stop":
            await self.cam.dvrip.ptz("DirectionUp", preset=-1, ch=channel)
        else:
            await self.cam.dvrip.ptz(cmd, step=step, preset=preset, ch=channel)
```
